### ISSUE TITLE
Hide settings icon before onboarding

### ISSUE THREAD

**Issue by arranf** [trys/JournalBook#18]
Mozilla Firefox Latest

There is a settings gear in the top right that isn't clickable!

**Comment by trys** [comment]
Before you've onboarded, the settings cog takes you to `/get-started`. Hence it doesn't take you anywhere. Maybe that's weird? What do you reckon?

The point was to push users through onboarding before they hit the heavier settings page, just in case they clicked the settings icon straight away on a fresh launch. I guess the icon could be hidden on the home page when you're not onboarded, then appear on `/get-started`. Clicking on it would flag you as 'onboarded' from that point and the home page would go back to normal.

**Comment by arranf** [comment]
I think hiding it makes sense if you're already on get-started! I was
playing on new machine and it felt like it was broken.

**Comment by trys** [comment]
Cool, I'll add it to the roadmap!
