### ISSUE TITLE
The order of the questions is lost when importing/exporting

### ISSUE THREAD

**Issue by alvarogarcia7** [trys/JournalBook#44]
After exporting the data, when reimporting, the order is lost

Behaviour I'd expect: the questions are still ordered by 'when' they where created (in ascending chronological order)

Behaviour I see: random order 

I believe this has to do with the importing (https://github.com/trys/JournalBook/blob/1fd6d9bbcdc0403d916045517585cd1bd8d7422b/src/routes/settings/index.js#L118 or https://github.com/trys/JournalBook/blob/1fd6d9bbcdc0403d916045517585cd1bd8d7422b/src/routes/settings/index.js#L132) or when showing questions (it is not ordering questions, just doing a 'getAll')

**Comment by alvarogarcia7** [comment]
Thank you very much for fixing this! After testing it, it works as desired :)

👍

**Comment by trys** [comment]
Wonderful, glad to hear it!
