### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by timnovis** [trys/JournalBook#5]
- Should we prevent users from adding/amending entries from previous days?
- Should we prevent pagination to before their first entry? If not, it might be nice to show a "No entry for this day" message instead of blank textareas/question fields
- Should we prevent users from navigating to the future through URL manipulation?

<img width="863" alt="screenshot 2018-12-31 at 17 10 33" src="https://user-images.githubusercontent.com/867553/50564690-0b862a00-0d1f-11e9-8170-1545a448e200.png">

**Comment by trys** [comment]
1. It's an interesting one, I wonder whether a previous day should be 'locked', and you choose to unlock it for editing? If you miss a day, or write up yesterday's notes the next morning, it would be frustrating to not be able to update it. I think it should be a 'paper-like' as possible.

2. That would be neat, I doubt many would want to go back before 'Day 0'. A 'No entry yet' message for non-today days would be really nice.

3. hmm, unsure. Could/would/should this be used as a future prompt? It's not a calendar, so maybe not? Given future pagination is disabled, it should really redirect a user back to today if future/bad dates are entered.

**Comment by timnovis** [comment]
1. Agreed, I think the current day’s view should be the only one in constant “edit mode” and all other days should be disabled by default. 

2. A nicer empty state sounds like a good solution then, just in case people want to retroactively add entries (and keeps it as paper-like as possible), no point in disabling pagination before day 0?

3. A redirect to the current day sounds like a good idea if bad dates are submitted.

**Comment by trys** [comment]
That all sounds good to me, I've added this issue to the roadmap

**Comment by timnovis** [comment]
Merged a change to redirect if bad dates entered, closing this issue in favour of #10
